version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-fullstack}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fullstack123}
      POSTGRES_DB: ${POSTGRES_DB:-playground}
      PGDATA: /data/postgres
    volumes:
      - postgres_vol:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres_net

networks:
  postgres_net:
    driver: bridge

volumes:
  postgres_vol:
  pgadmin_vol: